services:

  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: python-rabbitmq
    networks:
      - internal
    environment:
      RABBITMQ_HOST: "queue"
      RABBITMQ_SERVER_QUEUE: "rpc_server_queue"
      RABBITMQ_CLIENT_QUEUE: "rpc_client_queue"
      RABBITMQ_USER: "${RABBITMQ_DEFAULT_USER:-user}"
      RABBITMQ_PASS: "${RABBITMQ_DEFAULT_PASS:-password}"
    volumes:
      - ./app:/app

  queue:
    image: rabbitmq:3.11-management-alpine
    restart: always
    networks:
      - internal
    expose:
      - 5672
    ports:
      - 15672:15672 # RabbitMQ management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER:-user}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS:-password}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
volumes:
  rabbitmq_data:

networks:
  internal:
  web:
    external: ${EXTERNAL_NETWORK:-true}
    name: ${NETWORK_NAME:-proxy}

